imu0:
  T_i_b:
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.005
  accelerometer_random_walk: 6.0e-05
  accelerometers:
    M:
    - [0.9984135141141987, 0.0, 0.0]
    - [0.003918673493126846, 1.0027262149917109, 0.0]
    - [-0.012757691013082108, -0.011658763256373536, 0.9955590097767922]
  gyroscope_noise_density: 0.0005
  gyroscope_random_walk: 5.0e-06
  gyroscopes:
    A:
    - [-6.874322952144496e-05, -0.00025813755601277117, 0.00012107796905851057]
    - [0.00015192219447795596, 0.0009899969191237423, -2.447090423033517e-05]
    - [7.426939959748751e-05, -7.115296809571899e-05, -0.00022608656188170185]
    C_gyro_i:
    - [0.9999390676739714, -0.003207683344711017, 0.010562750913890456]
    - [0.003214473059776934, 0.999994637702091, -0.0006258833852104778]
    - [-0.010560686637562846, 0.0006597989269298293, 0.9999440167144956]
    M:
    - [0.9783129672510638, 0.0, 0.0]
    - [-0.0014687849608639595, 1.0043888740835587, 0.0]
    - [0.014708719331068845, -0.001635363630331124, 1.0023957258635237]
  model: scale-misalignment
  rostopic: /feature_tracker_imu/imu
  time_offset: 0.0
  update_rate: 205.0
